@extends('layouts.app')
@section('title', 'Verifikasi Pembayaran - Laundry Wash')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold mb-1">Pembayaran</h1><p class="text-muted mb-0">Verifikasi pembayaran transfer, QRIS, dan tunai.</p></div><form><select name="status" class="form-select" onchange="this.form.submit()"><option value="">Semua status</option>@foreach(\App\Enums\PaymentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select></form></div>
<div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Order</th><th>Customer</th><th>Metode</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($payments as $payment)<tr><td><a href="{{ route('admin.orders.show', $payment->order) }}">{{ $payment->order->order_number }}</a></td><td>{{ $payment->order->customer->name }}</td><td>{{ $payment->method->label() }}<div class="small text-muted">{{ $payment->reference ?: '-' }}</div></td><td class="fw-semibold">Rp {{ number_format($payment->amount, 0, ',', '.') }}</td><td><span class="badge {{ $payment->status->badgeClass() }}">{{ $payment->status->label() }}</span></td><td>@if($payment->status === \App\Enums\PaymentStatus::PENDING)<div class="d-flex gap-2"><form method="POST" action="{{ route('admin.payments.verify', $payment) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="paid"><button class="btn btn-sm btn-success" onclick="return confirm('Konfirmasi pembayaran ini?')">Terima</button></form><form method="POST" action="{{ route('admin.payments.verify', $payment) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="failed"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Tolak pembayaran ini?')">Tolak</button></form></div>@else<span class="small text-muted">{{ $payment->verifier?->name ?: '-' }}</span>@endif</td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-5">Belum ada pembayaran.</td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white">{{ $payments->links() }}</div></div>
@endsection
