@extends('layouts.app')

@section('title', 'Laundry Wash — Antar Jemput Laundry')

@push('styles')
<style>
.catalog-page { --ink:#25211d; --orange:#ef5b2a; --orange-deep:#d74720; --yellow:#f7c542; --sky:#ffd9c1; --cream:#fff2e8; background:var(--cream); }
.catalog-page .workspace-navbar { min-height:76px; margin:0; border:0; border-bottom:1px solid #f5c7a8; border-radius:0; background:#fff8f1!important; box-shadow:none!important; }
.catalog-page .workspace-navbar .container { max-width:none; padding-inline:32px; }
.catalog-page .workspace-navbar .container { position:relative; }
.catalog-page .catalog-primary-nav { position:absolute; left:50%; top:50%; gap:28px; transform:translate(-50%,-50%); white-space:nowrap; }
.catalog-page .catalog-primary-nav a { color:var(--ink); font-size:.78rem; font-weight:600; text-decoration:none; transition:color .18s ease; }
.catalog-page .catalog-primary-nav a:hover { color:var(--orange); }
.catalog-page .navbar-brand { color:var(--ink)!important; font-size:1.1rem; font-weight:700; }
.catalog-page .navbar-brand .text-info { color:var(--orange)!important; }
.catalog-page .navbar-brand i { display:grid; place-items:center; width:34px; height:34px; border-radius:11px; color:#fff; background:var(--orange); }
.catalog-page .workspace-navbar .nav-link { color:var(--ink)!important; font-size:.78rem; font-weight:500; }
.catalog-page .workspace-navbar .nav-link:hover { color:var(--orange)!important; text-decoration:underline; text-underline-offset:4px; }
.catalog-page .workspace-navbar .btn-primary { color:#fff; background:var(--orange); border-color:var(--orange); box-shadow:none; font-weight:700; }
.catalog-page .workspace-navbar .btn-primary:hover { color:#fff; background:#d94a23; border-color:#d94a23; }
.catalog-page .app-sidebar,.catalog-page .sidebar-backdrop,.catalog-page .mobile-bottom-nav,.catalog-page .mobile-sidebar-toggle,.catalog-page .workspace-page-title { display:none!important; }.catalog-page .app-content { margin:0!important; padding:0!important; } .catalog-page .app-content>.container { max-width:none; }
.catalog-page > footer { display:none; } .catalog { overflow:hidden; color:var(--ink); background:var(--cream); }
.catalog section { scroll-margin-top:84px; }
.catalog-hero { position:relative; min-height:550px; overflow:hidden; background:radial-gradient(circle at 8% 24%,transparent 0 27px,rgba(255,255,255,.28) 28px 30px,transparent 31px),radial-gradient(circle at 91% 27%,rgba(255,255,255,.2) 0 23px,transparent 24px),radial-gradient(circle at 82% 78%,transparent 0 39px,rgba(255,255,255,.25) 40px 42px,transparent 43px),linear-gradient(150deg,#d94c24 0%,#f06b37 55%,#ffa26e 100%); }
.catalog-hero::after { content:""; position:absolute; z-index:1; inset:auto -10% -56px; height:150px; border-radius:50% 50% 0 0 / 75% 75% 0 0; background:var(--cream); }
.catalog-hero-inner { position:relative; z-index:2; display:grid; grid-template-columns:minmax(0,.95fr) minmax(340px,1.05fr); gap:32px; align-items:center; max-width:1200px; min-height:550px; margin:auto; padding:78px 24px 100px; }
.catalog-hero-inner > :first-child { min-width:0; }
.catalog-kicker { display:inline-flex; gap:8px; align-items:center; padding:7px 12px; border-radius:999px; background:rgba(255,255,255,.72); font-size:.75rem; font-weight:600; } .catalog-kicker i { color:var(--orange); }
.catalog-hero h1 { max-width:580px; margin:17px 0; font-size:clamp(2.35rem,5.2vw,4.75rem); line-height:.98; letter-spacing:-.075em; font-weight:700; }.catalog-hero h1 span { color:var(--ink); }
.catalog-hero-copy { max-width:490px; color:#56362b; font-size:1rem; line-height:1.75; }
.catalog-hero-actions { display:flex; align-items:center; flex-wrap:wrap; gap:14px; margin-top:28px; }.catalog-cta { min-height:52px; padding:13px 23px; border:0; border-radius:14px; color:#201707; background:var(--yellow); box-shadow:0 5px 0 rgba(185,128,6,.22); font-weight:700; transition:transform .2s ease,box-shadow .2s ease; }.catalog-cta:hover { color:#201707; background:#ffd45e; transform:translateY(-2px); box-shadow:0 7px 0 rgba(185,128,6,.22); }
.catalog-hero-note { display:inline-flex; gap:8px; align-items:center; color:#512c20; font-size:.78rem; font-weight:500; }
.catalog-visual { position:relative; min-height:360px; }.catalog-visual::before { content:""; position:absolute; width:min(34vw,410px); aspect-ratio:1; top:0; right:5%; border-radius:49% 51% 42% 58% / 55% 38% 62% 45%; background:#ffe5a4; transform:rotate(-9deg); }
.hero-washer { position:absolute; z-index:2; right:39%; bottom:10px; width:225px; height:265px; border:12px solid #fff8ed; border-radius:36px 36px 28px 28px; background:var(--orange); box-shadow:0 24px 35px rgba(74,73,49,.18); transform:rotate(-5deg); }
.hero-washer::before { content:""; position:absolute; top:20px; left:23px; width:78px; height:17px; border-radius:20px; background:#ffd96d; box-shadow:92px 0 #f8f2e6; }.hero-washer::after { content:""; position:absolute; bottom:24px; left:29px; width:142px; height:142px; border:12px solid #fff8ed; border-radius:50%; background:radial-gradient(circle at 42% 34%,#d4f7fb 0 11%,#52bdd6 12% 52%,#19738c 53% 100%); }
.hero-folds { position:absolute; z-index:3; right:6%; bottom:21px; width:240px; height:220px; transform:rotate(8deg); }.hero-folds span { position:absolute; left:0; right:0; height:62px; border-radius:32px 22px 30px 21px; box-shadow:0 12px 15px rgba(79,85,74,.13); }.hero-folds span:nth-child(1){top:0;left:24px;width:190px;background:#fffef6}.hero-folds span:nth-child(2){top:55px;width:232px;background:var(--yellow)}.hero-folds span:nth-child(3){top:110px;left:16px;width:206px;background:#f8f3e8}.hero-folds span:nth-child(4){top:165px;left:3px;width:220px;background:#f68859}
.hero-spark { position:absolute; z-index:3; display:grid; place-items:center; width:34px; height:34px; border-radius:50%; color:#fff; background:var(--yellow); font-size:.9rem; }.hero-spark.one{right:8%;top:40px}.hero-spark.two{right:51%;top:26px;width:22px;height:22px;background:var(--orange)}.hero-spark.three{right:1%;top:142px;width:17px;height:17px;background:#fff;color:var(--orange)}
.catalog-section { max-width:1120px; margin:0 auto; padding:76px 24px; }.catalog-section-title { margin-bottom:8px; font-size:clamp(1.7rem,3vw,2.4rem); letter-spacing:-.05em; text-align:center; font-weight:700; }.catalog-section-lead { max-width:540px; margin:auto; color:#6f6860; text-align:center; line-height:1.7; }
.how-grid { position:relative; display:grid; grid-template-columns:repeat(3,1fr); gap:38px; margin-top:48px; }.how-grid::before { content:""; position:absolute; top:49px; right:16%; left:16%; border-top:2px dashed #f1c546; }.how-card { position:relative; text-align:center; }.how-icon { display:grid; place-items:center; width:96px; height:96px; margin:0 auto 18px; border:8px solid #fff9e9; border-radius:50%; color:var(--orange); background:#fff2bd; box-shadow:0 9px 23px rgba(205,147,36,.14); font-size:2rem; }.how-card:nth-child(2) .how-icon{color:#1c94b1;background:#d7f5fa}.how-card:nth-child(3) .how-icon{color:#b84320;background:#ffe1cb}.how-card h3 { font-size:1rem; font-weight:700; }.how-card p { max-width:245px; margin:0 auto; color:#716a63; font-size:.86rem; line-height:1.7; }
.service-band { position:relative; overflow:hidden; background:#fff0c7; }.service-band::before,.service-band::after { content:""; position:absolute; width:45vw; height:120px; border-radius:50%; background:var(--cream); }.service-band::before{top:-67px;left:-10vw}.service-band::after{top:-78px;right:-9vw}.service-band .catalog-section { position:relative; z-index:1; }.catalog-services { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:16px; margin-top:42px; }.service-card { display:flex; flex-direction:column; min-height:270px; padding:25px; border:1px solid rgba(157,103,13,.12); border-radius:24px; background:rgba(255,255,255,.88); box-shadow:0 12px 30px rgba(141,109,34,.08); transition:transform .2s ease,box-shadow .2s ease; }.service-card:hover { transform:translateY(-4px); box-shadow:0 18px 36px rgba(141,109,34,.14); }.service-card-icon{display:grid;place-items:center;width:52px;height:52px;margin-bottom:20px;border-radius:17px;color:#fff;background:var(--orange);font-size:1.35rem}.service-card:nth-child(2n) .service-card-icon{background:#14a0bf}.service-card:nth-child(3n) .service-card-icon{background:#eda820}.service-card h3{font-size:1.1rem;font-weight:700}.service-card p{color:#716a63;font-size:.83rem;line-height:1.65}.service-meta{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-top:auto;padding-top:18px;border-top:1px solid #eee1be}.service-price{font-size:1.24rem;font-weight:700;letter-spacing:-.04em}.service-price small{color:#756d64;font-size:.75rem;font-weight:500}.service-duration{color:#6b5821;font-size:.73rem;white-space:nowrap}
.catalog-trust { display:grid; grid-template-columns:.8fr 1.2fr; gap:56px; align-items:center; }.trust-visual { position:relative; min-height:310px; overflow:hidden; border-radius:34px; background:var(--orange); }.trust-visual::before { content:""; position:absolute; top:42px; left:50%; width:280px; height:280px; border-radius:50%; background:#ffd256; transform:translateX(-50%); }.trust-truck { position:absolute; z-index:2; right:23%; bottom:38px; width:210px; height:115px; border-radius:28px 30px 12px 13px; background:#fffdf3; box-shadow:inset -45px 0 #ffdd78,0 13px 0 rgba(88,46,26,.14); }.trust-truck::before,.trust-truck::after { content:""; position:absolute; bottom:-22px; width:45px; height:45px; border:9px solid #342d29; border-radius:50%; background:#ffcf47; }.trust-truck::before{left:25px}.trust-truck::after{right:22px}.trust-truck i{position:absolute;top:31px;left:22px;color:var(--orange);font-size:1.7rem}.catalog-trust h2{font-size:clamp(1.75rem,3vw,2.65rem);letter-spacing:-.06em;font-weight:700}.catalog-trust p{color:#6b6560;line-height:1.8}.trust-list{display:grid;gap:13px;padding:0;margin:23px 0 0;list-style:none}.trust-list li{display:flex;gap:10px;align-items:start}.trust-list i{color:var(--orange)}
.catalog-end { padding:68px 24px 92px; color:#fffaf2; background:var(--orange-deep); text-align:center; }.catalog-end h2{font-size:clamp(1.9rem,4vw,3.2rem);letter-spacing:-.06em;font-weight:700}.catalog-end p{max-width:570px;margin:14px auto 26px;color:#ffe6cf}.catalog-page .btn:focus-visible,.catalog-page a:focus-visible{outline:3px solid #7c2815;outline-offset:4px}
.catalog-footer { display:grid; grid-template-columns:1fr auto 1fr; align-items:center; gap:24px; min-height:68px; padding:14px 32px; color:#c9c9c9; background:#303030; border-top:1px solid #4a4a4a; font-size:.78rem; }.catalog-footer-brand{display:flex;align-items:center;justify-self:start;gap:9px;color:#fff;font-weight:700;font-size:.94rem}.catalog-footer-brand i{display:grid;place-items:center;width:28px;height:28px;border-radius:8px;background:#f15b2a}.catalog-footer>span{text-align:center}.catalog-footer-links{display:flex;justify-self:end;justify-content:flex-end;flex-wrap:wrap;gap:20px}.catalog-footer a{color:#dedede;text-decoration:none}.catalog-footer a:hover{color:#fff;text-decoration:underline;text-underline-offset:3px}
@media(max-width:767.98px){.catalog-footer{grid-template-columns:1fr;justify-items:start;gap:14px;padding:24px 20px;text-align:left}.catalog-footer>span{order:3;text-align:left;font-size:.72rem}.catalog-footer-links{order:2;width:100%;justify-content:flex-start;gap:16px;padding-top:14px;border-top:1px solid #4a4a4a}}
@media(max-width:575.98px){.catalog-page .workspace-navbar .container{flex-wrap:nowrap;padding-inline:14px}.catalog-page .workspace-navbar .navbar-collapse{display:flex!important;flex:0 0 auto;width:auto}.catalog-page .workspace-navbar .navbar-nav{flex-wrap:nowrap;gap:0!important}.catalog-page .navbar-brand{min-width:0;margin-right:auto;font-size:.92rem}.catalog-page .navbar-brand i{width:30px;height:30px}.catalog-page .workspace-navbar .btn{padding-inline:10px;font-size:.68rem;white-space:nowrap}.catalog-page .workspace-navbar .nav-link{padding-inline:6px;font-size:.72rem;white-space:nowrap}.catalog-hero-actions{align-items:stretch;flex-direction:column;gap:10px}.catalog-hero-actions .catalog-cta{width:100%;justify-content:center}.catalog-hero-note{justify-content:center}.catalog-footer{min-height:0;padding:22px 18px}.catalog-footer-links{font-size:.75rem}}
@media(max-width:991.98px){.catalog-hero-inner{grid-template-columns:1fr;min-height:auto;padding-top:56px}.catalog-visual{width:100%;max-width:530px;min-height:320px;margin:auto}.catalog-hero h1{max-width:650px}.catalog-trust{grid-template-columns:1fr;gap:34px}.trust-visual{width:100%;max-width:560px;margin:auto}}@media(max-width:767.98px){.catalog-page .workspace-navbar{min-height:64px;margin:0;border-radius:0}.catalog-page .workspace-navbar .container{padding-inline:16px}.catalog-page .navbar-brand span{font-size:.95rem}.catalog-page .workspace-navbar .navbar-collapse{flex-grow:0}.catalog-page .workspace-navbar .navbar-nav{flex-direction:row;align-items:center;gap:3px}.catalog-page .workspace-navbar .btn{min-height:40px;padding:8px 12px;font-size:.72rem}.catalog-page .workspace-navbar .nav-link{padding-inline:7px}.catalog-hero-inner{gap:0;padding:48px 20px 76px}.catalog-hero h1{font-size:clamp(2.2rem,12vw,3.3rem)}.catalog-hero-copy{font-size:.91rem}.catalog-hero-note{display:block;margin:13px 0 0}.catalog-visual{min-height:267px}.hero-washer{right:auto;left:2%;transform:scale(.8) rotate(-5deg);transform-origin:bottom left}.hero-folds{right:-4%;transform:scale(.76) rotate(8deg);transform-origin:bottom right}.catalog-section{padding:58px 20px}.how-grid{grid-template-columns:1fr;gap:29px;margin-top:34px}.how-grid::before{display:none}.how-icon{margin-bottom:12px}.catalog-services{grid-template-columns:1fr}.service-card{min-height:0}.catalog-trust{gap:26px}.catalog-end{padding:58px 20px 82px}}@media(prefers-reduced-motion:reduce){.catalog-page *{scroll-behavior:auto!important;transition:none!important}}
</style>
@endpush

@section('content')
<div class="catalog">
<section class="catalog-hero" aria-labelledby="catalog-hero-title"><div class="catalog-hero-inner"><div>
<span class="catalog-kicker"><i class="bi bi-stars" aria-hidden="true"></i>Laundry antar-jemput</span>
<h1 id="catalog-hero-title">Cucian bersih, <span>hidup lebih ringan.</span></h1>
<p class="catalog-hero-copy">Atur penjemputan dari rumah, pantau prosesnya, lalu terima kembali cucian yang sudah rapi. Semua dalam satu alur yang jelas.</p>
<div class="catalog-hero-actions">@guest <a class="btn catalog-cta" href="{{ route('register') }}">Jadwalkan penjemputan</a>
@else @if(auth()->user()->isCustomer())<a class="btn catalog-cta" href="{{ route('customer.orders.create') }}">Jadwalkan penjemputan</a>@endif @endguest
<span class="catalog-hero-note"><i class="bi bi-geo-alt-fill" aria-hidden="true"></i>Pickup dan delivery oleh kurir</span></div></div>
<div class="catalog-visual" aria-hidden="true"><span class="hero-spark one"><i class="bi bi-star-fill"></i></span><span class="hero-spark two"></span><span class="hero-spark three"></span><div class="hero-washer"></div><div class="hero-folds"><span></span><span></span><span></span><span></span></div></div></div></section>
<section id="cara-kerja" class="catalog-section" aria-labelledby="how-title"><h2 id="how-title" class="catalog-section-title">Laundry semudah tiga langkah.</h2><p class="catalog-section-lead">Bukan drop-off: kurir menjemput dan mengantarkan kembali cucianmu.</p><div class="how-grid"><article class="how-card"><div class="how-icon"><i class="bi bi-calendar2-check" aria-hidden="true"></i></div><h3>Atur penjemputan</h3><p>Pilih layanan, alamat, tanggal, dan jam yang nyaman untukmu.</p></article><article class="how-card"><div class="how-icon"><i class="bi bi-bicycle" aria-hidden="true"></i></div><h3>Kurir menjemput</h3><p>Lacak perjalanan kurir saat menuju alamatmu dari aplikasi.</p></article><article class="how-card"><div class="how-icon"><i class="bi bi-house-check" aria-hidden="true"></i></div><h3>Diantar kembali</h3><p>Bayar ketika laundry siap, lalu kurir mengantar sampai rumah.</p></article></div></section>
<section id="layanan" class="service-band" aria-labelledby="services-title"><div class="catalog-section"><h2 id="services-title" class="catalog-section-title">Pilih layananmu.</h2><p class="catalog-section-lead">Harga dan estimasi di bawah diambil langsung dari layanan aktif Laundry Wash.</p><div class="catalog-services">@forelse($services as $service)<article class="service-card" aria-labelledby="service-{{ $service->id }}"><div class="service-card-icon"><i class="bi bi-basket2" aria-hidden="true"></i></div><h3 id="service-{{ $service->id }}">{{ $service->name }}</h3><p>{{ $service->description ?: 'Layanan laundry kiloan dengan proses antar-jemput kurir.' }}</p><div class="service-meta"><span class="service-price">Rp {{ number_format($service->price_per_kg, 0, ',', '.') }}<small>/kg</small></span><span class="service-duration"><i class="bi bi-clock me-1" aria-hidden="true"></i>Estimasi {{ $service->estimated_hours }} jam</span></div></article>@empty<div class="service-card text-center"><div class="service-card-icon mx-auto"><i class="bi bi-basket2" aria-hidden="true"></i></div><h3>Layanan belum tersedia</h3><p>Belum ada layanan aktif saat ini. Silakan cek kembali nanti.</p></div>@endforelse</div></div></section>
<section id="tentang-kami" class="catalog-section"><div class="catalog-trust"><div class="trust-visual" aria-hidden="true"><div class="trust-truck"><i class="bi bi-droplet-half"></i></div></div><div><h2>Dari pintu rumahmu, kembali ke pintu rumahmu.</h2><p>Tidak perlu membawa keranjang ke outlet. Laundry Wash dirancang untuk alur antar-jemput yang transparan dari pesanan sampai cucian selesai.</p><ul class="trust-list"><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i><span><strong>Status jelas.</strong> Pantau tahap pencucian dari akunmu.</span></li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i><span><strong>Tracking kurir.</strong> Posisi kurir tampil saat penjemputan dan pengantaran aktif.</span></li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i><span><strong>Pembayaran praktis.</strong> QRIS atau Virtual Account ketika laundry sudah siap.</span></li></ul></div></div></section>
<section class="catalog-end" aria-labelledby="catalog-end-title"><h2 id="catalog-end-title">Siapkan cucianmu. Kami yang jemput.</h2><p>Buat akun, pilih layanan, lalu atur jadwal penjemputan sesuai waktumu.</p>
@guest
<a class="btn catalog-cta" href="{{ route('register') }}">Mulai buat pesanan</a>
@else
@if(auth()->user()->isCustomer())
<a class="btn catalog-cta" href="{{ route('customer.orders.create') }}">Buat pesanan</a>
@endif
@endguest
</section>
<footer class="catalog-footer"><a class="catalog-footer-brand" href="{{ url('/') }}"><i class="bi bi-droplet-half" aria-hidden="true"></i><span>Laundry Wash</span></a><span>&copy; {{ date('Y') }} Laundry Wash</span><nav class="catalog-footer-links" aria-label="Tautan footer"><a href="#cara-kerja">Cara kerja</a><a href="#layanan">Layanan</a><a href="#tentang-kami">Tentang kami</a></nav></footer>
</div>
@endsection
